version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: swift_db
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: swift_db
    ports:
      - '5432:5432'
